name: Publish Godot Game

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: paulloz/godot-action@v1.2.2
        with:
          version: 4.1
      - run: |
          mkdir EXPORT
          
          godot --version
          godot --export "Web" EXPORT/index.html 
